[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.41.1",
    "fastapi>=0.121.3",
    "mangum>=0.19.0",
    "openai>=2.8.1",
    "pypdf>=6.3.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
